### ISSUE TITLE
check-*

### ISSUE THREAD

**Issue by dustinkirkland** [CanonicalLtd/ubuntu-advantage-script#64]
For each of the enable-* / disable-* actions, please create a third action, check-*, which prints a message to stdout and exits 0 if enabled, 1 if disabled.

For example:
 $ ubuntu-advantage check-fips
 FIPS is enabled
 $ echo $?
 0

 $ ubuntu-advantage check-landscape
 Landscape is disabled
 $ echo $?
 1

This should provide a definitive mechanism for third party tools checking if a machine is running in FIPS-enabled mode, or if a machine has Livepatch enabled, or if a machine has a support contract, etc.

Thanks!
Dustin

**Comment by panlinux** [comment]
We have is-*-enabled commands that have an exit status that indicates whether the feature is enabled or not. It's not documented and was initially meant to be used by motd scripts only. Does that suffice?
```
ubuntu@xenial-pam-mysql-1574911:~$ ubuntu-advantage is-fips-enabled
ubuntu@xenial-pam-mysql-1574911:~$ echo $?
1
ubuntu@xenial-pam-mysql-1574911:~$ ubuntu-advantage is-esm-enabled
ubuntu@xenial-pam-mysql-1574911:~$ echo $?
1
ubuntu@xenial-pam-mysql-1574911:~$ ubuntu-advantage is-livepatch-enabled
ubuntu@xenial-pam-mysql-1574911:~$ echo $?
127
```
This last one is annoying, it's because the snap isn't installed. We were only concerned with a != 0 result, so 127 or 1 was fine. If it returns 0, the feature is enabled. Anything else means it's not enabled.

BTW, you can use this daily PPA for trying things out, it's a build from master: ppa:ahasenack/pam-mysql-scrambled-1574911

**Comment by panlinux** [comment]
Fixed the PPA address :)

**Comment by dustinkirkland** [comment]
That's perfect!!!  Thanks.

**Comment by panlinux** [comment]
Closing as the current is-*-enabled commands suffice.
